# Generated by Django 4.2.7 on 2023-11-14 03:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoAplicacion', '0002_profesor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='curso',
            old_name='nombre',
            new_name='curso',
        ),
    ]
