# Generated by Django 4.2.7 on 2023-11-29 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoAplicacion', '0004_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Casa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion', models.CharField(max_length=40)),
                ('ambientes', models.IntegerField()),
                ('metros_cuadrados', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion', models.CharField(max_length=40)),
                ('piso', models.IntegerField()),
                ('departamento', models.CharField(max_length=40)),
                ('ambientes', models.IntegerField()),
                ('metros_cuadrados', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Curso',
        ),
        migrations.DeleteModel(
            name='Profesor',
        ),
    ]
