# Generated by Django 4.2.7 on 2023-11-30 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoAplicacion', '0006_casa_imagen_casa_precio_departamento_imagen_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casa',
            name='imagen',
            field=models.ImageField(blank=True, default='5411.jpeg', null=True, upload_to='casas'),
        ),
        migrations.AlterField(
            model_name='departamento',
            name='imagen',
            field=models.ImageField(blank=True, default='5411.jpeg', null=True, upload_to='departamentos'),
        ),
    ]
