# Generated by Django 4.2.7 on 2023-12-01 03:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoAplicacion', '0008_alter_avatar_imagen'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Estudiante',
            new_name='Dueño',
        ),
        migrations.DeleteModel(
            name='Entregable',
        ),
    ]
