# Generated by Django 4.2.7 on 2023-12-01 20:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoAplicacion', '0010_alter_avatar_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='casa',
            name='user',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
